# This file was generated by GoReleaser. DO NOT EDIT.
class Jocasta < Formula
  desc "Logger for CLI tool from standard I/O"
  homepage ""
  version "1.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/marema31/jocasta/releases/download/v1.0.5/jocasta_1.0.5_Darwin_x86_64.tar.gz"
    sha256 "d1ca8f12409826c5f79f4f84794b4cfb42ca60ffcbd8182c96b0a85e7c783f86"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/marema31/jocasta/releases/download/v1.0.5/jocasta_1.0.5_Linux_x86_64.tar.gz"
      sha256 "4583a82a0765ef1bca4be428dfc48262c2374e7d6d21c4de0bd43c26f544bc08"
    end
  end

  def install
    bin.install "jocasta"
  end
end
