# This file was generated by GoReleaser. DO NOT EDIT.
class Kamino < Formula
  desc "Development database content bootstraper"
  homepage ""
  version "1.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/marema31/kamino/releases/download/v1.3.0/kamino_1.3.0_Darwin_x86_64.tar.gz"
    sha256 "d5a9c023f6dba18b50754bd8f14770ef4203e5c5ceaddb69fe28d2152baf74b9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/marema31/kamino/releases/download/v1.3.0/kamino_1.3.0_Linux_x86_64.tar.gz"
      sha256 "b49c4e58a276191ee813bb56790895985788abc53756a989197b19dae92a1c0d"
    end
  end

  def install
    bin.install "kamino"
  end
end
