# This file was generated by GoReleaser. DO NOT EDIT.
class Kamino < Formula
  desc "Development database content bootstraper"
  homepage ""
  version "1.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/marema31/kamino/releases/download/v1.5.0/kamino_1.5.0_Darwin_x86_64.tar.gz"
    sha256 "589d2df6a5e01e8eff4203d5fbf578fda8bd60e68c1dab4b2ac11d6b8120864d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/marema31/kamino/releases/download/v1.5.0/kamino_1.5.0_Linux_x86_64.tar.gz"
      sha256 "30298bcc6a89e53db8c1e150a5c1eddfa74de9543e5f024c0d63179795dbc8f5"
    end
  end

  def install
    bin.install "kamino"
  end
end
