# This file was generated by GoReleaser. DO NOT EDIT.
class Villip < Formula
  desc "Filtering proxy for development environment"
  homepage ""
  version "1.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/marema31/villip/releases/download/v1.0.2/villip_1.0.2_Darwin_x86_64.tar.gz"
    sha256 "695de2d36d6d59a1d16973b9f215d8c70c5abd1da91d7c8499e7ccd898b62479"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/marema31/villip/releases/download/v1.0.2/villip_1.0.2_Linux_x86_64.tar.gz"
      sha256 "55d34ab77a21fe30ca7930723d324d49829ec9de2b97f17bf1e3622d01d5eae3"
    end
  end

  def install
    bin.install "villip"
  end
end
