# This file was generated by GoReleaser. DO NOT EDIT.
class Villip < Formula
  desc "Filtering proxy for development environment"
  homepage ""
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/marema31/villip/releases/download/v1.0.1/villip_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "5ab4b4c75f3e36892bc9414d1006452d080216f088f052cca1fe34db16a9b22f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/marema31/villip/releases/download/v1.0.1/villip_1.0.1_Linux_x86_64.tar.gz"
      sha256 "88b83e77f00b898e3ada20848b89ec4d4d9b38643866977c2ab9f435d7e710b6"
    end
  end

  def install
    bin.install "villip"
  end
end
